name: Deploy to Cloud Run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Build and push Docker
 image
      - run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/dropshipping-bot/dropshipping-bot:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/dropshipping-bot/dropshipping-bot:latest
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dropshipping-bot \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/dropshipping-bot/dropshipping-bot:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --port=5000 \
            --service-account=${{ secrets.SA_EMAIL }}
      - name: Trigger Workflow
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature: sha1=$(echo -n '${{ secrets.WEBHOOK_SECRET }}' | openssl dgst -sha1 -hmac '${{ secrets.WEBHOOK_SECRET }}')" \
            -d '{}' \
            https://dropshipping-bot-${{ secrets.GCP_PROJECT }}.a.run.app/start_workflow
